### ISSUE TITLE
Calling whenScroll() after DOMContentLoaded

### ISSUE THREAD

**Issue by djgrant** [callumacrae/when-scroll#3]
```
whenScroll('above 1000px', function () {
    console.log('You haven\'t even scrolled yet');
}, true);
```

If you run this after `DOMContentLoaded`, is the expected behaviour for the scroll handler to be called?

I'm doing this in a react component where the component may re-mount after the DOM has loaded. 

Happy to create a PR if you agree that the scroll handler should be called as long as the DOM is loaded rather than _when_ the DOM has loaded.

**Comment by callumacrae** [comment]
Checking `document.readyState` would make a lot of sense: feel free to send a PR and I'll deal with it asap.
